builder:
  track: dev

labels:
  app-group: estafette-controllers
  team: estafette-team
  language: golang

version:
  semver:
    major: 1
    minor: 2

stages:
  build:
    image: golang:1.13.4-alpine3.10
    env:
      CGO_ENABLED: 0
      GOOS: linux
    commands:
    - go test ./...
    - go build -a -installsuffix cgo -ldflags "-X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_GIT_NAME} .

  bake:
    image: extensions/docker:dev
    action: build
    repositories:
    - estafette
    path: ./publish
    copy:
    - /etc/ssl/certs/ca-certificates.crt

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    repositories:
    - estafette

  lint-helm-chart:
    image: extensions/helm:dev
    action: lint
    prerelease: true

  package-helm-chart:
    image: extensions/helm:dev
    action: package
    prerelease: true

  test-helm-chart:
    services:
    - name: kubernetes
      image: bsycorp/kind:latest-1.12
      ports:
      - port: 8443
      - port: 10080
        readiness:
          path: /kubernetes-ready
          timeoutSeconds: 180
    image: extensions/helm:dev
    action: test
    prerelease: true
    values:
    - secret.googleServiceAccountKeyfileJson='estafette.secret(UK3lQTzhnSB0ZOve.mmY7chCLH3w-_7jsv06teOPp4-Q6Eux5hsTtucqVje0f6n_dY4xGZtVd_ucE91LDPbXb8gFwjw5DyztSkIUWMePgG70DwONnHKZ-q7DL6bxojfrCiPZqG8HpIsUk_aJX3I7XJFwuuVP1xq6tMlRZUEhvgTth8X0u0JzCjIq6O6m5yy-hpkr8TkeUcrTDBNz6EoAsmIDMKMtjzYqcniUUjja7YarBX9CpMUbQPbkDdE1XEl7sdbs1FQSCBk0_Xs2kdiLSmYWLMExc0igRE_WHgmjZ72_BzBoivjLPYB3UNSFh21n7TNpnutySh3s7yw8qtuul7obxaWyhMuA7VLUd4uD_uQpi-0zaGH76h_WhHrYmxNd1LF4RFd-pS4bGwgSrtcIIDZ5Abp2UbzttVIObRp-tOaZbGDWw9_kjr_53Ij6fWcwSMxDq7_34nDldsWuErsR_2ycm6nU95aRESHT2ihwDxxYXYtkFd3ZkOfTXDB5iMFEhplhdoHw2kCE5eDwndy-5ZX0J9hpdiPumiMFHxLyo6oroGDxGn-cVVMxEoQs585hBnlTs53v0YJAGFsZJ1CR3igsl64I41SnukAVmh_Pma4e6q5nHdeyzOEX2NnOTc8tTKMYUbY_Bho_TtuBfKZOGmYV7KTL53Uclw3PIrbxoWmRv5mMSrjpJKogPrFtPpZa63csI8W-U-NJtMb77JXH3-kWXZCy6iZeB5ASVE8FXTHiHu3-ttI3l4aRLf71sA9y5Qgox7DcFfReYOLqjzAo9TF-nc4FgSyKOgT-Xm9WS37ybixeW4XjM0x10CKzGybR28JBAsl3WBCs-l28MwZn5KUSqw8XNukx8SxsFONlbtmohs5coS0gE2GchjwT_0FVptadEVNzGmWGSL--9WHU87fasNC98f6mASLbwEm1MOR_vTHDw-qlSw6GFl-7bzVFligB-hxQL5ZR58A2o5TdmvDRP16Bu2sEdikY_OII9gmo377RzkFuyd4TivJBSmSiz5wp-ihnzPKCAOaJKeoO74vY2p6OBJUSnFi-65SdZtUNKUCn52Uo_w2WcFYf9vt8-zg_sJouWsBnZXYxXCm0ohGrZnHY7bGC-qqRDzfuujRz5yJoebnBHkYmFLAsDk1rksSSjAksLvQku5eEVY4hVgJmTzzWfXHMWYkO99dWkdpb0YPUpIiJnEnB_xf5pAW2s2LNdzGivd17Xnc-O9fsBZVDJ4jzjljsWIgEJLm_OC9hNszdAqI9qmu9R6Xb7S2SzQUfeZhBHZvsonairFTimT_HWeRpgcbkiaYED4Pztdyjtc0AgmXHrepZzmYL1EAqVJu4lN_pN4iT7YS80K3AYw1mtXkVMzCXiOBR_JPpx6AGm_zFgrOwmxAzTpt-NkFeYlWbdQ8UXBQ0cCQqQ4fy9eZLz2SY54fhW-98wBgC0F7pNXLLVBEdqD8h6LbIRPHY0p5YzQLEIIzA4K-GgoZesRpJzlycpZ4aASmSKJ31uOpAr6qGkOfe54_zni51mj7XlXFgjofjw0r-72ZOvNMFQWuYlH-m8ComGGMi-PdhxyRr6lOeetQj1g7zCLpAwj0RWPwZoyqwBFy92OWH8ZhRjsLTvDlNPR_lu4K20yc-ZC4JwfZ6LFsLoXrpUahGCVnZr7pEfc-uHIIG2NELSQx1JjyN4NYNPRVZY33g9J_FTm_b_opTsUsgjkYzluoRFAdCIpuVPkAxSnGJ4SNwAbVBJUmn9Jjvgyo3V38kis-fA8qybVlYlk5wUGu0k2a7pTWrf6Dz2IoSCll69X5foyCEmpCm2O69JBODoMFp4BfeAaL5vRo-9yr9VRxV_XFpGNxxlrmeAFEKx2tBvgwjTiDiMSlmiFW874k2UaFz0n7U8wGCnXI_Ec4U45n8lVz_5NIPPGRBKAoGssIUgcVW66gwNGcRjaYyzgvdP78T6XMoVdtkv1f9t_EEwbaxY8noTj5cjnbEJqZCaSPlFSJDCGzNMX4-Ff9SZNltUnn3-7_4gZDuPwKqOciNWVEel0K7Xwhs0YiJFhMSifo9dA-mGSoTrl-LeKE7OdIR0JUxin18FWZ0BNSTBPPjJGKtx5bLmBSD17-jmN5Kzw-pyNWgiDFt72EB3UZsp6jLdU8zP2FSgNuxGra_2lzQjlgUCa5XFwzT2SgGcEch6vN33G7XNb0OmTzdvJfjr0f08kpkEFuvfaDL6UYYyByUs6zbM1VjsGvRncNIXAXAgNyxJdnyhavcBsg1XyQgRaOw5pZfNb4X1QzxwixVLhcrS7m0kv1XIYySk0YJdZHTKKswXOFnMWj9bwXqNv8dcBaGDyl91d_4_Okg6Qg_VHttSyNtiQmHG4w0MpBjn2bU0IXUqPR-yGybXQ3G8VRUcYp5iQ11f5riu3dfkF-ju9UB2aEOWjRwy9qtAOiQmTZpDT86LfPhzdUNyfYvcV2LZNVDWyDMeyghOW2sratMcK0h2It9Wfsc9m0bzDB6nPL_OAaV0MKyfcurCJy4dQRLTCQWdv_EVo1J3njs2Oqw-kSs5k9p7cCIqvjPuUHeI5p3G3PLdEk__VWudOC_ryZTyygkq8RpQiLNIbxxpbwuMJNrB1aauPUubmp0uIdHB6bLbwMMPpurW2VEbaC5R1AqBKSGuQ8GQj8jMS9H4C7c2QcCoqaHgFV3ltnSpCkgGu9_RcFnYzTumv5x3VKvpizT99lz1MZzd3h7sdnGUy5crn-8Z8TUtV3truvUEZ2_M3t9Sky-00JbDk7tkJnp10WHACJ_ymGZZbv0IqrNH3dykQt5S59ShNek_TZibRpKbvEFd6B3Hdporiv66DbLQubqK0EfkqbMzJ2kmfxRjkRru5x6w1kcb6xk0bU0YuJa3zyw7P1N4a2ejpxl2V2leW9RX8B8NVZX49p6s9FZUzEiEAD1EnXNGbcZArKho1LxBd_FrcfnsI7uTvwPaeGkaGQRaX9-we4nHOJw4taUBtntNBLRleLnl95Rcl8jCJg8uHFwkOVY-tyrffPOFG-qv3MYzwTxumjTwSoJsXyn6Xo7h75LUN5m3RBsEVY6R_TwAN-RKCMc-5_AjMen7jZrD3G_Ek0x4EXed0-5Hg1JYLh9FtdkQDB_J6xmqpamb6Q==)'

  clone-charts-repo:
    image: extensions/git-clone:dev
    repo: helm-charts
    branch: master

  publish-helm-chart:
    image: extensions/helm:dev
    action: publish
    prerelease: true

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'failed'

releases:
  release:
    clone: true
    stages:
      package-helm-chart:
        image: extensions/helm:dev
        action: package

      clone-charts-repo:
        image: extensions/git-clone:dev
        repo: helm-charts
        branch: master

      publish-helm-chart:
        image: extensions/helm:dev
        action: publish
        purgePrerelease: true

      create-github-release:
        image: extensions/github-release:dev
        version: ${ESTAFETTE_BUILD_VERSION_MAJOR}.${ESTAFETTE_BUILD_VERSION_MINOR}.0
        closeMilestone: true