{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "estafette-gke-node-pool-shifter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-gke-node-pool-shifter.labels" . | indent 4 }}
{{- end -}}
