{{- if .Values.rbac.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "estafette-gke-node-pool-shifter.fullname" . }}
  labels:
{{ include "estafette-gke-node-pool-shifter.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "estafette-gke-node-pool-shifter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "estafette-gke-node-pool-shifter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
