{{- if .Values.rbac.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "estafette-gke-node-pool-shifter.fullname" . }}
  labels:
{{ include "estafette-gke-node-pool-shifter.labels" . | indent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - nodes
  verbs:
  - get
  - list
{{- end -}}
